package com.gondor.parking.constant;

public class ParkingLotError {
	
	public static final String PARKING_LOT_NOT_AVAILABLE_EXCEPTION = "PARKING LOT IS FULL"; 
	
	public static final String PARKING_LOT_IS_FULL_FOR_VIP = "PARKING LOT IS FULL FOR VIP";
	
	public static final String PARKING_LOT_IS_FULL_FOR_REGULAR_CUSTOMER = "PARKING LOT IS FULL FOR REGULAR CUTSOMER";
	
	public static final String NO_VECHILE_WITH_THIS_REGISTRATION_NO  ="NO VEHCILE PARKED IN PARKING LOT WITH THIS REGISTRATION NO AND VEHICLE TYPE";
	
	public static final String PARKING_FLOOR_NEGATIVE_ERROR = "PLEASE ENTER VALID FlOOR NUMBER, PARKING FLOOR CANNOT BE NEGATIVE";

	public static final String PARKING_FLOOR_MAX_REACH_ERROR = "PLEASE ENTER PARKING BETWEEN 1 To 20. YOU CANNOT CREATE PARKING LOT WITH FLOOR MORE THAN 20 ";
	
	public static final String OPERATION_NOT_AVAILABLE_ERROR = "THIS OPERATION IS NOT AVAILABLE.PLEASE CONTACT ADMIN FOR MORE CLARIFICATION";
	
	public static final String WRONG_USER_INPUT_ERROR = "PLEASE SELECT CORRECT CHOICE FROM MENU";

}
